# 日志配置
logging:
  level:
    io.modelcontextprotocol: INFO
    org.springframework.ai.mcp: INFO
    com.agent.springbootmcphosts: INFO # 自定义项目日志级别

# 自定义配置
mcp:
  rag:
    url: http://localhost:8906
    debug-url: http://localhost:8906
