<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
	<modelVersion>4.0.0</modelVersion>
	<!--引入父工程依赖-->
	<parent>
		<groupId>com.agent</groupId>
		<artifactId>springboot-agent</artifactId>
		<version>0.0.1-SNAPSHOT</version>
		<relativePath>../pom.xml</relativePath> <!-- lookup parent from repository -->
	</parent>
	<groupId>com.agent</groupId>
	<artifactId>springboot-rag</artifactId>
	<version>0.0.1-SNAPSHOT</version>
	<name>springboot-rag</name>
	<description>springboot-rag</description>

	<dependencies>

		<!-- 强制使用 Spring MVC（Servlet 栈），避免 WebFlux NIO 线程阻塞冲突 -->
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-web</artifactId>
		</dependency>

		<!-- 引入Redis Chat Memory依赖 -->
		<dependency>
			<groupId>org.springframework.ai</groupId>
			<artifactId>spring-ai-starter-model-chat-memory-repository-redis</artifactId>
		</dependency>

		<!-- 引入RAG依赖 -->
		<dependency>
			<groupId>org.springframework.ai</groupId>
			<artifactId>spring-ai-rag</artifactId>
		</dependency>

		<!-- 引入Ollama依赖 -->
		<dependency>
			<groupId>org.springframework.ai</groupId>
			<artifactId>spring-ai-starter-model-ollama</artifactId>
		</dependency>

		<!-- 引入Milvus依赖 -->
		<dependency>
			<groupId>org.springframework.ai</groupId>
			<artifactId>spring-ai-starter-vector-store-milvus</artifactId>
		</dependency>

		<!-- 引入Neo4j依赖 -->
<!--		<dependency>-->
<!--			<groupId>org.springframework.ai</groupId>-->
<!--			<artifactId>spring-ai-starter-vector-store-neo4j</artifactId>-->
<!--		</dependency>-->
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-data-neo4j</artifactId>
		</dependency>

		<!-- LangGraph4j 核心 -->
		<dependency>
			<groupId>org.bsc.langgraph4j</groupId>
			<artifactId>langgraph4j-core</artifactId>
		</dependency>

		<!-- LangGraph4j 集成 -->
		<dependency>
			<groupId>org.bsc.langgraph4j</groupId>
			<artifactId>langgraph4j-spring-ai</artifactId>
		</dependency>

		<!-- LangGraph4j AgentExecutor -->
		<dependency>
			<groupId>org.bsc.langgraph4j</groupId>
			<artifactId>langgraph4j-springai-agentexecutor</artifactId>
		</dependency>

		<!-- LangGraph4j Studio -->
		<dependency>
			<groupId>org.bsc.langgraph4j</groupId>
			<artifactId>langgraph4j-studio-springboot</artifactId>
		</dependency>

	</dependencies>

	<build>
		<plugins>
			<plugin>
				<groupId>org.springframework.boot</groupId>
				<artifactId>spring-boot-maven-plugin</artifactId>
			</plugin>
		</plugins>
	</build>

</project>
